// LED
#define LED_TYPE WS2811
#define LED_PIN GPIO_NUM_13
#define LED_MODE GRB
#define LED_DEFAULT_COUNT 50
#define DEFAULT_DELAY 50
#define DEFAULT_BRIGHTNESS 255

// Wi Fi
#define DEFAULT_SSID "LEDTape"
#define DEFAULT_PASS "admin678"